---

- hosts: all

  sudo: yes

  vars: 
      host: $inventory_hostname

  tasks:
    - name: 필수 패키지 설치 확인
      apt: pkg=nginx,git,python3,python3-pip state=present
    - name: make sure virtualenv is installed
      shell: pip3 install virtualenv

    - name: nginx에서 긴 호스트명 허용
      lineinfile: 
        dest=/etc/nginx/nginx.conf 
        regexp='(\s+)#? ?server_names_hash_bucket_size' 
        backrefs=yes
        line='\1server_names_hash_bucket_size 64;'

    - name: nginx 설정을 sites-available에 추가
      template: src=./nginx.conf.j2 dest=/etc/nginx/sites-available/{{ host }}
      notify:
          - restart nginx

    - name: nginx sites-enabled 링크 추가
      file: src=/etc/nginx/sites-available/{{ host }} dest=/etc/nginx/sites-enabled/{{ host }} state=link
      notify:
          - restart nginx


    - name: gunicorn 초기화 스크립트
      template: src=./gunicorn-upstart.conf.j2 dest=/etc/init/gunicorn-{{ host }}.conf
      notify:
          - restart gunicorn

    - name: nginx가 실행되는지 확인
      service: name=nginx state=running
    - name: make sure gunicorn is running
      service: name=gunicorn-{{ host }} state=running

  handlers:
    - name: nginx 재시작
      service:  name=nginx state=restarted

    - name: gunicorn 재시작
      service:  name=gunicorn-{{ host }} state=restarted
